version: '3.8'

services:
  fe:
    image: ynnub2804/fe_jewelry_management
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
    tty: true

  be:
    image: ynnub2804/be_jewelry_management
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    tty: true
