/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JewelryApis);
  }
}(this, function(expect, JewelryApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JewelryApis.CreateInvoiceSellPayload();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateInvoiceSellPayload', function() {
    it('should create an instance of CreateInvoiceSellPayload', function() {
      // uncomment below and update the code to test CreateInvoiceSellPayload
      //var instance = new JewelryApis.CreateInvoiceSellPayload();
      //expect(instance).to.be.a(JewelryApis.CreateInvoiceSellPayload);
    });

    it('should have the property transactionType (base name: "transactionType")', function() {
      // uncomment below and update the code to test the property transactionType
      //var instance = new JewelryApis.CreateInvoiceSellPayload();
      //expect(instance).to.be();
    });

    it('should have the property customerName (base name: "customerName")', function() {
      // uncomment below and update the code to test the property customerName
      //var instance = new JewelryApis.CreateInvoiceSellPayload();
      //expect(instance).to.be();
    });

    it('should have the property customerPhone (base name: "customerPhone")', function() {
      // uncomment below and update the code to test the property customerPhone
      //var instance = new JewelryApis.CreateInvoiceSellPayload();
      //expect(instance).to.be();
    });

    it('should have the property invoiceItems (base name: "invoiceItems")', function() {
      // uncomment below and update the code to test the property invoiceItems
      //var instance = new JewelryApis.CreateInvoiceSellPayload();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethod (base name: "paymentMethod")', function() {
      // uncomment below and update the code to test the property paymentMethod
      //var instance = new JewelryApis.CreateInvoiceSellPayload();
      //expect(instance).to.be();
    });

  });

}));
