/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JewelryApis);
  }
}(this, function(expect, JewelryApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JewelryApis.Invoice();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Invoice', function() {
    it('should create an instance of Invoice', function() {
      // uncomment below and update the code to test Invoice
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be.a(JewelryApis.Invoice);
    });

    it('should have the property invoiceId (base name: "invoiceId")', function() {
      // uncomment below and update the code to test the property invoiceId
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property transactionDate (base name: "transactionDate")', function() {
      // uncomment below and update the code to test the property transactionDate
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property transactionType (base name: "transactionType")', function() {
      // uncomment below and update the code to test the property transactionType
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property customerName (base name: "customerName")', function() {
      // uncomment below and update the code to test the property customerName
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property customerPhone (base name: "customerPhone")', function() {
      // uncomment below and update the code to test the property customerPhone
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property transactionClerk (base name: "transactionClerk")', function() {
      // uncomment below and update the code to test the property transactionClerk
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property transactionClerkId (base name: "transactionClerkId")', function() {
      // uncomment below and update the code to test the property transactionClerkId
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property totalAmount (base name: "totalAmount")', function() {
      // uncomment below and update the code to test the property totalAmount
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property taxPercent (base name: "taxPercent")', function() {
      // uncomment below and update the code to test the property taxPercent
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property totalDiscount (base name: "totalDiscount")', function() {
      // uncomment below and update the code to test the property totalDiscount
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property totalVoucherDiscount (base name: "totalVoucherDiscount")', function() {
      // uncomment below and update the code to test the property totalVoucherDiscount
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property netAmount (base name: "netAmount")', function() {
      // uncomment below and update the code to test the property netAmount
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property paymentDetailsId (base name: "paymentDetailsId")', function() {
      // uncomment below and update the code to test the property paymentDetailsId
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property invoiceItems (base name: "invoiceItems")', function() {
      // uncomment below and update the code to test the property invoiceItems
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethod (base name: "paymentMethod")', function() {
      // uncomment below and update the code to test the property paymentMethod
      //var instance = new JewelryApis.Invoice();
      //expect(instance).to.be();
    });

  });

}));
