/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JewelryApis);
  }
}(this, function(expect, JewelryApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JewelryApis.MetalTypeCreateDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetalTypeCreateDto', function() {
    it('should create an instance of MetalTypeCreateDto', function() {
      // uncomment below and update the code to test MetalTypeCreateDto
      //var instance = new JewelryApis.MetalTypeCreateDto();
      //expect(instance).to.be.a(JewelryApis.MetalTypeCreateDto);
    });

    it('should have the property metalTypeName (base name: "metalTypeName")', function() {
      // uncomment below and update the code to test the property metalTypeName
      //var instance = new JewelryApis.MetalTypeCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property metalPurity (base name: "metalPurity")', function() {
      // uncomment below and update the code to test the property metalPurity
      //var instance = new JewelryApis.MetalTypeCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property metalGroupName (base name: "metalGroupName")', function() {
      // uncomment below and update the code to test the property metalGroupName
      //var instance = new JewelryApis.MetalTypeCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property isAutoUpdatePrice (base name: "isAutoUpdatePrice")', function() {
      // uncomment below and update the code to test the property isAutoUpdatePrice
      //var instance = new JewelryApis.MetalTypeCreateDto();
      //expect(instance).to.be();
    });

    it('should have the property isOnMonitor (base name: "isOnMonitor")', function() {
      // uncomment below and update the code to test the property isOnMonitor
      //var instance = new JewelryApis.MetalTypeCreateDto();
      //expect(instance).to.be();
    });

  });

}));
