/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JewelryApis);
  }
}(this, function(expect, JewelryApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JewelryApis.ProductPriceDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductPriceDto', function() {
    it('should create an instance of ProductPriceDto', function() {
      // uncomment below and update the code to test ProductPriceDto
      //var instance = new JewelryApis.ProductPriceDto();
      //expect(instance).to.be.a(JewelryApis.ProductPriceDto);
    });

    it('should have the property productPriceId (base name: "productPriceId")', function() {
      // uncomment below and update the code to test the property productPriceId
      //var instance = new JewelryApis.ProductPriceDto();
      //expect(instance).to.be();
    });

    it('should have the property totalMetalCost (base name: "totalMetalCost")', function() {
      // uncomment below and update the code to test the property totalMetalCost
      //var instance = new JewelryApis.ProductPriceDto();
      //expect(instance).to.be();
    });

    it('should have the property totalGemstoneCost (base name: "totalGemstoneCost")', function() {
      // uncomment below and update the code to test the property totalGemstoneCost
      //var instance = new JewelryApis.ProductPriceDto();
      //expect(instance).to.be();
    });

    it('should have the property laborCost (base name: "laborCost")', function() {
      // uncomment below and update the code to test the property laborCost
      //var instance = new JewelryApis.ProductPriceDto();
      //expect(instance).to.be();
    });

    it('should have the property markupPercentage (base name: "markupPercentage")', function() {
      // uncomment below and update the code to test the property markupPercentage
      //var instance = new JewelryApis.ProductPriceDto();
      //expect(instance).to.be();
    });

    it('should have the property salePrice (base name: "salePrice")', function() {
      // uncomment below and update the code to test the property salePrice
      //var instance = new JewelryApis.ProductPriceDto();
      //expect(instance).to.be();
    });

  });

}));
