/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GemstoneDto model module.
 * @module model/GemstoneDto
 * @version 1.0.0
 */
class GemstoneDto {
    /**
     * Constructs a new <code>GemstoneDto</code>.
     * @alias module:model/GemstoneDto
     * @param gemstoneName {String} 
     */
    constructor(gemstoneName) { 
        
        GemstoneDto.initialize(this, gemstoneName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gemstoneName) { 
        obj['gemstoneName'] = gemstoneName;
    }

    /**
     * Constructs a <code>GemstoneDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GemstoneDto} obj Optional instance to populate.
     * @return {module:model/GemstoneDto} The populated <code>GemstoneDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GemstoneDto();

            if (data.hasOwnProperty('gemstoneId')) {
                obj['gemstoneId'] = ApiClient.convertToType(data['gemstoneId'], 'Number');
            }
            if (data.hasOwnProperty('gemstoneName')) {
                obj['gemstoneName'] = ApiClient.convertToType(data['gemstoneName'], 'String');
            }
            if (data.hasOwnProperty('stoneColor')) {
                obj['stoneColor'] = ApiClient.convertToType(data['stoneColor'], 'String');
            }
            if (data.hasOwnProperty('stoneCut')) {
                obj['stoneCut'] = ApiClient.convertToType(data['stoneCut'], 'String');
            }
            if (data.hasOwnProperty('stoneClarity')) {
                obj['stoneClarity'] = ApiClient.convertToType(data['stoneClarity'], 'String');
            }
            if (data.hasOwnProperty('materialWeight')) {
                obj['materialWeight'] = ApiClient.convertToType(data['materialWeight'], 'Number');
            }
            if (data.hasOwnProperty('materialSize')) {
                obj['materialSize'] = ApiClient.convertToType(data['materialSize'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GemstoneDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GemstoneDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GemstoneDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['gemstoneName'] && !(typeof data['gemstoneName'] === 'string' || data['gemstoneName'] instanceof String)) {
            throw new Error("Expected the field `gemstoneName` to be a primitive type in the JSON string but got " + data['gemstoneName']);
        }
        // ensure the json data is a string
        if (data['stoneColor'] && !(typeof data['stoneColor'] === 'string' || data['stoneColor'] instanceof String)) {
            throw new Error("Expected the field `stoneColor` to be a primitive type in the JSON string but got " + data['stoneColor']);
        }
        // ensure the json data is a string
        if (data['stoneCut'] && !(typeof data['stoneCut'] === 'string' || data['stoneCut'] instanceof String)) {
            throw new Error("Expected the field `stoneCut` to be a primitive type in the JSON string but got " + data['stoneCut']);
        }
        // ensure the json data is a string
        if (data['stoneClarity'] && !(typeof data['stoneClarity'] === 'string' || data['stoneClarity'] instanceof String)) {
            throw new Error("Expected the field `stoneClarity` to be a primitive type in the JSON string but got " + data['stoneClarity']);
        }

        return true;
    }


}

GemstoneDto.RequiredProperties = ["gemstoneName"];

/**
 * @member {Number} gemstoneId
 */
GemstoneDto.prototype['gemstoneId'] = undefined;

/**
 * @member {String} gemstoneName
 */
GemstoneDto.prototype['gemstoneName'] = undefined;

/**
 * @member {String} stoneColor
 */
GemstoneDto.prototype['stoneColor'] = undefined;

/**
 * @member {String} stoneCut
 */
GemstoneDto.prototype['stoneCut'] = undefined;

/**
 * @member {String} stoneClarity
 */
GemstoneDto.prototype['stoneClarity'] = undefined;

/**
 * @member {Number} materialWeight
 */
GemstoneDto.prototype['materialWeight'] = undefined;

/**
 * @member {Number} materialSize
 */
GemstoneDto.prototype['materialSize'] = undefined;






export default GemstoneDto;

