/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetalTypeDto model module.
 * @module model/MetalTypeDto
 * @version 1.0.0
 */
class MetalTypeDto {
    /**
     * Constructs a new <code>MetalTypeDto</code>.
     * @alias module:model/MetalTypeDto
     * @param metalTypeName {String} 
     * @param materialWeight {Number} 
     */
    constructor(metalTypeName, materialWeight) { 
        
        MetalTypeDto.initialize(this, metalTypeName, materialWeight);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metalTypeName, materialWeight) { 
        obj['metalTypeName'] = metalTypeName;
        obj['materialWeight'] = materialWeight;
    }

    /**
     * Constructs a <code>MetalTypeDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetalTypeDto} obj Optional instance to populate.
     * @return {module:model/MetalTypeDto} The populated <code>MetalTypeDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetalTypeDto();

            if (data.hasOwnProperty('metalTypeId')) {
                obj['metalTypeId'] = ApiClient.convertToType(data['metalTypeId'], 'Number');
            }
            if (data.hasOwnProperty('metalTypeName')) {
                obj['metalTypeName'] = ApiClient.convertToType(data['metalTypeName'], 'String');
            }
            if (data.hasOwnProperty('metalPurity')) {
                obj['metalPurity'] = ApiClient.convertToType(data['metalPurity'], 'Number');
            }
            if (data.hasOwnProperty('metalGroupName')) {
                obj['metalGroupName'] = ApiClient.convertToType(data['metalGroupName'], 'String');
            }
            if (data.hasOwnProperty('materialWeight')) {
                obj['materialWeight'] = ApiClient.convertToType(data['materialWeight'], 'Number');
            }
            if (data.hasOwnProperty('materialSize')) {
                obj['materialSize'] = ApiClient.convertToType(data['materialSize'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetalTypeDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetalTypeDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MetalTypeDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['metalTypeName'] && !(typeof data['metalTypeName'] === 'string' || data['metalTypeName'] instanceof String)) {
            throw new Error("Expected the field `metalTypeName` to be a primitive type in the JSON string but got " + data['metalTypeName']);
        }
        // ensure the json data is a string
        if (data['metalGroupName'] && !(typeof data['metalGroupName'] === 'string' || data['metalGroupName'] instanceof String)) {
            throw new Error("Expected the field `metalGroupName` to be a primitive type in the JSON string but got " + data['metalGroupName']);
        }

        return true;
    }


}

MetalTypeDto.RequiredProperties = ["metalTypeName", "materialWeight"];

/**
 * @member {Number} metalTypeId
 */
MetalTypeDto.prototype['metalTypeId'] = undefined;

/**
 * @member {String} metalTypeName
 */
MetalTypeDto.prototype['metalTypeName'] = undefined;

/**
 * @member {Number} metalPurity
 */
MetalTypeDto.prototype['metalPurity'] = undefined;

/**
 * @member {String} metalGroupName
 */
MetalTypeDto.prototype['metalGroupName'] = undefined;

/**
 * @member {Number} materialWeight
 */
MetalTypeDto.prototype['materialWeight'] = undefined;

/**
 * @member {Number} materialSize
 */
MetalTypeDto.prototype['materialSize'] = undefined;






export default MetalTypeDto;

