/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetalTypeUpdateDto model module.
 * @module model/MetalTypeUpdateDto
 * @version 1.0.0
 */
class MetalTypeUpdateDto {
    /**
     * Constructs a new <code>MetalTypeUpdateDto</code>.
     * @alias module:model/MetalTypeUpdateDto
     */
    constructor() { 
        
        MetalTypeUpdateDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetalTypeUpdateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetalTypeUpdateDto} obj Optional instance to populate.
     * @return {module:model/MetalTypeUpdateDto} The populated <code>MetalTypeUpdateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetalTypeUpdateDto();

            if (data.hasOwnProperty('metalGroupName')) {
                obj['metalGroupName'] = ApiClient.convertToType(data['metalGroupName'], 'String');
            }
            if (data.hasOwnProperty('isAutoUpdatePrice')) {
                obj['isAutoUpdatePrice'] = ApiClient.convertToType(data['isAutoUpdatePrice'], 'Boolean');
            }
            if (data.hasOwnProperty('isOnMonitor')) {
                obj['isOnMonitor'] = ApiClient.convertToType(data['isOnMonitor'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetalTypeUpdateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetalTypeUpdateDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['metalGroupName'] && !(typeof data['metalGroupName'] === 'string' || data['metalGroupName'] instanceof String)) {
            throw new Error("Expected the field `metalGroupName` to be a primitive type in the JSON string but got " + data['metalGroupName']);
        }

        return true;
    }


}



/**
 * The metal group name
 * @member {String} metalGroupName
 */
MetalTypeUpdateDto.prototype['metalGroupName'] = undefined;

/**
 * Allow metal auto update price through fetch api. Default is false
 * @member {Boolean} isAutoUpdatePrice
 */
MetalTypeUpdateDto.prototype['isAutoUpdatePrice'] = undefined;

/**
 * Allow metal show price on monitor. Default is false
 * @member {Boolean} isOnMonitor
 */
MetalTypeUpdateDto.prototype['isOnMonitor'] = undefined;






export default MetalTypeUpdateDto;

