/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetalPriceUpdateDto model module.
 * @module model/MetalPriceUpdateDto
 * @version 1.0.0
 */
class MetalPriceUpdateDto {
    /**
     * Constructs a new <code>MetalPriceUpdateDto</code>.
     * @alias module:model/MetalPriceUpdateDto
     */
    constructor() { 
        
        MetalPriceUpdateDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetalPriceUpdateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetalPriceUpdateDto} obj Optional instance to populate.
     * @return {module:model/MetalPriceUpdateDto} The populated <code>MetalPriceUpdateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetalPriceUpdateDto();

            if (data.hasOwnProperty('profitSell')) {
                obj['profitSell'] = ApiClient.convertToType(data['profitSell'], 'Number');
            }
            if (data.hasOwnProperty('profitBuy')) {
                obj['profitBuy'] = ApiClient.convertToType(data['profitBuy'], 'Number');
            }
            if (data.hasOwnProperty('metalPriceSpot')) {
                obj['metalPriceSpot'] = ApiClient.convertToType(data['metalPriceSpot'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetalPriceUpdateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetalPriceUpdateDto</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Percent rate of profit sell
 * @member {Number} profitSell
 */
MetalPriceUpdateDto.prototype['profitSell'] = undefined;

/**
 * Percent rate of profit buy
 * @member {Number} profitBuy
 */
MetalPriceUpdateDto.prototype['profitBuy'] = undefined;

/**
 * Spot price of the metal in VND per gram
 * @member {Number} metalPriceSpot
 */
MetalPriceUpdateDto.prototype['metalPriceSpot'] = undefined;






export default MetalPriceUpdateDto;

