/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetalPriceCreateDto model module.
 * @module model/MetalPriceCreateDto
 * @version 1.0.0
 */
class MetalPriceCreateDto {
    /**
     * Constructs a new <code>MetalPriceCreateDto</code>.
     * @alias module:model/MetalPriceCreateDto
     * @param profitSell {Number} Percent rate of profit sell
     * @param profitBuy {Number} Percent rate of profit buy
     * @param metalPriceSpot {Number} Spot price of the metal in VND per gram
     */
    constructor(profitSell, profitBuy, metalPriceSpot) { 
        
        MetalPriceCreateDto.initialize(this, profitSell, profitBuy, metalPriceSpot);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, profitSell, profitBuy, metalPriceSpot) { 
        obj['profitSell'] = profitSell;
        obj['profitBuy'] = profitBuy;
        obj['metalPriceSpot'] = metalPriceSpot;
    }

    /**
     * Constructs a <code>MetalPriceCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetalPriceCreateDto} obj Optional instance to populate.
     * @return {module:model/MetalPriceCreateDto} The populated <code>MetalPriceCreateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetalPriceCreateDto();

            if (data.hasOwnProperty('profitSell')) {
                obj['profitSell'] = ApiClient.convertToType(data['profitSell'], 'Number');
            }
            if (data.hasOwnProperty('profitBuy')) {
                obj['profitBuy'] = ApiClient.convertToType(data['profitBuy'], 'Number');
            }
            if (data.hasOwnProperty('metalPriceSpot')) {
                obj['metalPriceSpot'] = ApiClient.convertToType(data['metalPriceSpot'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetalPriceCreateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetalPriceCreateDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MetalPriceCreateDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

MetalPriceCreateDto.RequiredProperties = ["profitSell", "profitBuy", "metalPriceSpot"];

/**
 * Percent rate of profit sell
 * @member {Number} profitSell
 */
MetalPriceCreateDto.prototype['profitSell'] = undefined;

/**
 * Percent rate of profit buy
 * @member {Number} profitBuy
 */
MetalPriceCreateDto.prototype['profitBuy'] = undefined;

/**
 * Spot price of the metal in VND per gram
 * @member {Number} metalPriceSpot
 */
MetalPriceCreateDto.prototype['metalPriceSpot'] = undefined;






export default MetalPriceCreateDto;

