/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetalPriceCreateDto from './MetalPriceCreateDto';
import MetalTypeCreateDto from './MetalTypeCreateDto';

/**
 * The MetalCreateRequest model module.
 * @module model/MetalCreateRequest
 * @version 1.0.0
 */
class MetalCreateRequest {
    /**
     * Constructs a new <code>MetalCreateRequest</code>.
     * @alias module:model/MetalCreateRequest
     * @param metalType {module:model/MetalTypeCreateDto} 
     * @param metalPrice {module:model/MetalPriceCreateDto} 
     */
    constructor(metalType, metalPrice) { 
        
        MetalCreateRequest.initialize(this, metalType, metalPrice);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metalType, metalPrice) { 
        obj['metalType'] = metalType;
        obj['metalPrice'] = metalPrice;
    }

    /**
     * Constructs a <code>MetalCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetalCreateRequest} obj Optional instance to populate.
     * @return {module:model/MetalCreateRequest} The populated <code>MetalCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetalCreateRequest();

            if (data.hasOwnProperty('metalType')) {
                obj['metalType'] = MetalTypeCreateDto.constructFromObject(data['metalType']);
            }
            if (data.hasOwnProperty('metalPrice')) {
                obj['metalPrice'] = MetalPriceCreateDto.constructFromObject(data['metalPrice']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetalCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetalCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MetalCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `metalType`
        if (data['metalType']) { // data not null
          MetalTypeCreateDto.validateJSON(data['metalType']);
        }
        // validate the optional field `metalPrice`
        if (data['metalPrice']) { // data not null
          MetalPriceCreateDto.validateJSON(data['metalPrice']);
        }

        return true;
    }


}

MetalCreateRequest.RequiredProperties = ["metalType", "metalPrice"];

/**
 * @member {module:model/MetalTypeCreateDto} metalType
 */
MetalCreateRequest.prototype['metalType'] = undefined;

/**
 * @member {module:model/MetalPriceCreateDto} metalPrice
 */
MetalCreateRequest.prototype['metalPrice'] = undefined;






export default MetalCreateRequest;

