/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetalTypeCreateDto model module.
 * @module model/MetalTypeCreateDto
 * @version 1.0.0
 */
class MetalTypeCreateDto {
    /**
     * Constructs a new <code>MetalTypeCreateDto</code>.
     * @alias module:model/MetalTypeCreateDto
     * @param metalTypeName {String} The name of metal
     * @param metalGroupName {String} The metal group name
     */
    constructor(metalTypeName, metalGroupName) { 
        
        MetalTypeCreateDto.initialize(this, metalTypeName, metalGroupName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metalTypeName, metalGroupName) { 
        obj['metalTypeName'] = metalTypeName;
        obj['metalGroupName'] = metalGroupName;
    }

    /**
     * Constructs a <code>MetalTypeCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetalTypeCreateDto} obj Optional instance to populate.
     * @return {module:model/MetalTypeCreateDto} The populated <code>MetalTypeCreateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetalTypeCreateDto();

            if (data.hasOwnProperty('metalTypeName')) {
                obj['metalTypeName'] = ApiClient.convertToType(data['metalTypeName'], 'String');
            }
            if (data.hasOwnProperty('metalPurity')) {
                obj['metalPurity'] = ApiClient.convertToType(data['metalPurity'], 'Number');
            }
            if (data.hasOwnProperty('metalGroupName')) {
                obj['metalGroupName'] = ApiClient.convertToType(data['metalGroupName'], 'String');
            }
            if (data.hasOwnProperty('isAutoUpdatePrice')) {
                obj['isAutoUpdatePrice'] = ApiClient.convertToType(data['isAutoUpdatePrice'], 'Boolean');
            }
            if (data.hasOwnProperty('isOnMonitor')) {
                obj['isOnMonitor'] = ApiClient.convertToType(data['isOnMonitor'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetalTypeCreateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetalTypeCreateDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MetalTypeCreateDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['metalTypeName'] && !(typeof data['metalTypeName'] === 'string' || data['metalTypeName'] instanceof String)) {
            throw new Error("Expected the field `metalTypeName` to be a primitive type in the JSON string but got " + data['metalTypeName']);
        }
        // ensure the json data is a string
        if (data['metalGroupName'] && !(typeof data['metalGroupName'] === 'string' || data['metalGroupName'] instanceof String)) {
            throw new Error("Expected the field `metalGroupName` to be a primitive type in the JSON string but got " + data['metalGroupName']);
        }

        return true;
    }


}

MetalTypeCreateDto.RequiredProperties = ["metalTypeName", "metalGroupName"];

/**
 * The name of metal
 * @member {String} metalTypeName
 */
MetalTypeCreateDto.prototype['metalTypeName'] = undefined;

/**
 * Percentage of purity
 * @member {Number} metalPurity
 */
MetalTypeCreateDto.prototype['metalPurity'] = undefined;

/**
 * The metal group name
 * @member {String} metalGroupName
 */
MetalTypeCreateDto.prototype['metalGroupName'] = undefined;

/**
 * Allow metal auto update price through fetch api. Default is false
 * @member {Boolean} isAutoUpdatePrice
 */
MetalTypeCreateDto.prototype['isAutoUpdatePrice'] = undefined;

/**
 * Allow metal show price on monitor. Default is false
 * @member {Boolean} isOnMonitor
 */
MetalTypeCreateDto.prototype['isOnMonitor'] = undefined;






export default MetalTypeCreateDto;

