/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetalPriceRate from './MetalPriceRate';

/**
 * The MetalType model module.
 * @module model/MetalType
 * @version 1.0.0
 */
class MetalType {
    /**
     * Constructs a new <code>MetalType</code>.
     * @alias module:model/MetalType
     */
    constructor() { 
        
        MetalType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetalType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetalType} obj Optional instance to populate.
     * @return {module:model/MetalType} The populated <code>MetalType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetalType();

            if (data.hasOwnProperty('metalTypeId')) {
                obj['metalTypeId'] = ApiClient.convertToType(data['metalTypeId'], 'Number');
            }
            if (data.hasOwnProperty('metalTypeName')) {
                obj['metalTypeName'] = ApiClient.convertToType(data['metalTypeName'], 'String');
            }
            if (data.hasOwnProperty('metalPurity')) {
                obj['metalPurity'] = ApiClient.convertToType(data['metalPurity'], 'Number');
            }
            if (data.hasOwnProperty('metalGroupName')) {
                obj['metalGroupName'] = ApiClient.convertToType(data['metalGroupName'], 'String');
            }
            if (data.hasOwnProperty('isAutoUpdatePrice')) {
                obj['isAutoUpdatePrice'] = ApiClient.convertToType(data['isAutoUpdatePrice'], 'Boolean');
            }
            if (data.hasOwnProperty('isOnMonitor')) {
                obj['isOnMonitor'] = ApiClient.convertToType(data['isOnMonitor'], 'Boolean');
            }
            if (data.hasOwnProperty('currentMetalPriceRate')) {
                obj['currentMetalPriceRate'] = MetalPriceRate.constructFromObject(data['currentMetalPriceRate']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetalType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetalType</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['metalTypeName'] && !(typeof data['metalTypeName'] === 'string' || data['metalTypeName'] instanceof String)) {
            throw new Error("Expected the field `metalTypeName` to be a primitive type in the JSON string but got " + data['metalTypeName']);
        }
        // ensure the json data is a string
        if (data['metalGroupName'] && !(typeof data['metalGroupName'] === 'string' || data['metalGroupName'] instanceof String)) {
            throw new Error("Expected the field `metalGroupName` to be a primitive type in the JSON string but got " + data['metalGroupName']);
        }
        // validate the optional field `currentMetalPriceRate`
        if (data['currentMetalPriceRate']) { // data not null
          MetalPriceRate.validateJSON(data['currentMetalPriceRate']);
        }

        return true;
    }


}



/**
 * @member {Number} metalTypeId
 */
MetalType.prototype['metalTypeId'] = undefined;

/**
 * @member {String} metalTypeName
 */
MetalType.prototype['metalTypeName'] = undefined;

/**
 * @member {Number} metalPurity
 */
MetalType.prototype['metalPurity'] = undefined;

/**
 * @member {String} metalGroupName
 */
MetalType.prototype['metalGroupName'] = undefined;

/**
 * @member {Boolean} isAutoUpdatePrice
 */
MetalType.prototype['isAutoUpdatePrice'] = undefined;

/**
 * @member {Boolean} isOnMonitor
 */
MetalType.prototype['isOnMonitor'] = undefined;

/**
 * @member {module:model/MetalPriceRate} currentMetalPriceRate
 */
MetalType.prototype['currentMetalPriceRate'] = undefined;






export default MetalType;

