/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductMaterial from './ProductMaterial';
import ProductPrice from './ProductPrice';

/**
 * The Product model module.
 * @module model/Product
 * @version 1.0.0
 */
class Product {
    /**
     * Constructs a new <code>Product</code>.
     * @alias module:model/Product
     */
    constructor() { 
        
        Product.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Product} obj Optional instance to populate.
     * @return {module:model/Product} The populated <code>Product</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Product();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('productType')) {
                obj['productType'] = ApiClient.convertToType(data['productType'], 'String');
            }
            if (data.hasOwnProperty('unitMeasure')) {
                obj['unitMeasure'] = ApiClient.convertToType(data['unitMeasure'], 'String');
            }
            if (data.hasOwnProperty('saleStatus')) {
                obj['saleStatus'] = ApiClient.convertToType(data['saleStatus'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedBy')) {
                obj['updatedBy'] = ApiClient.convertToType(data['updatedBy'], 'Number');
            }
            if (data.hasOwnProperty('productMaterials')) {
                obj['productMaterials'] = ApiClient.convertToType(data['productMaterials'], [ProductMaterial]);
            }
            if (data.hasOwnProperty('productPrice')) {
                obj['productPrice'] = ProductPrice.constructFromObject(data['productPrice']);
            }
            if (data.hasOwnProperty('imageUrls')) {
                obj['imageUrls'] = ApiClient.convertToType(data['imageUrls'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Product</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Product</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['productType'] && !(typeof data['productType'] === 'string' || data['productType'] instanceof String)) {
            throw new Error("Expected the field `productType` to be a primitive type in the JSON string but got " + data['productType']);
        }
        // ensure the json data is a string
        if (data['unitMeasure'] && !(typeof data['unitMeasure'] === 'string' || data['unitMeasure'] instanceof String)) {
            throw new Error("Expected the field `unitMeasure` to be a primitive type in the JSON string but got " + data['unitMeasure']);
        }
        // ensure the json data is a string
        if (data['saleStatus'] && !(typeof data['saleStatus'] === 'string' || data['saleStatus'] instanceof String)) {
            throw new Error("Expected the field `saleStatus` to be a primitive type in the JSON string but got " + data['saleStatus']);
        }
        if (data['productMaterials']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['productMaterials'])) {
                throw new Error("Expected the field `productMaterials` to be an array in the JSON data but got " + data['productMaterials']);
            }
            // validate the optional field `productMaterials` (array)
            for (const item of data['productMaterials']) {
                ProductMaterial.validateJSON(item);
            };
        }
        // validate the optional field `productPrice`
        if (data['productPrice']) { // data not null
          ProductPrice.validateJSON(data['productPrice']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['imageUrls'])) {
            throw new Error("Expected the field `imageUrls` to be an array in the JSON data but got " + data['imageUrls']);
        }

        return true;
    }


}



/**
 * @member {Number} productId
 */
Product.prototype['productId'] = undefined;

/**
 * @member {String} name
 */
Product.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Product.prototype['description'] = undefined;

/**
 * @member {String} productType
 */
Product.prototype['productType'] = undefined;

/**
 * @member {String} unitMeasure
 */
Product.prototype['unitMeasure'] = undefined;

/**
 * @member {String} saleStatus
 */
Product.prototype['saleStatus'] = undefined;

/**
 * @member {Date} updatedAt
 */
Product.prototype['updatedAt'] = undefined;

/**
 * @member {Number} updatedBy
 */
Product.prototype['updatedBy'] = undefined;

/**
 * @member {Array.<module:model/ProductMaterial>} productMaterials
 */
Product.prototype['productMaterials'] = undefined;

/**
 * @member {module:model/ProductPrice} productPrice
 */
Product.prototype['productPrice'] = undefined;

/**
 * @member {Array.<String>} imageUrls
 */
Product.prototype['imageUrls'] = undefined;






export default Product;

