/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SilverPriceRateDto model module.
 * @module model/SilverPriceRateDto
 * @version 1.0.0
 */
class SilverPriceRateDto {
    /**
     * Constructs a new <code>SilverPriceRateDto</code>.
     * @alias module:model/SilverPriceRateDto
     */
    constructor() { 
        
        SilverPriceRateDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SilverPriceRateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SilverPriceRateDto} obj Optional instance to populate.
     * @return {module:model/SilverPriceRateDto} The populated <code>SilverPriceRateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SilverPriceRateDto();

            if (data.hasOwnProperty('silverOunceInVnd')) {
                obj['silverOunceInVnd'] = ApiClient.convertToType(data['silverOunceInVnd'], 'Number');
            }
            if (data.hasOwnProperty('gmtOuncePriceUsdUpdated')) {
                obj['gmtOuncePriceUsdUpdated'] = ApiClient.convertToType(data['gmtOuncePriceUsdUpdated'], 'String');
            }
            if (data.hasOwnProperty('usdToVnd')) {
                obj['usdToVnd'] = ApiClient.convertToType(data['usdToVnd'], 'Number');
            }
            if (data.hasOwnProperty('gmtVndUpdated')) {
                obj['gmtVndUpdated'] = ApiClient.convertToType(data['gmtVndUpdated'], 'String');
            }
            if (data.hasOwnProperty('gramToOunceFormula')) {
                obj['gramToOunceFormula'] = ApiClient.convertToType(data['gramToOunceFormula'], 'Number');
            }
            if (data.hasOwnProperty('silverGramInUsd')) {
                obj['silverGramInUsd'] = ApiClient.convertToType(data['silverGramInUsd'], 'Number');
            }
            if (data.hasOwnProperty('silverGramInVnd')) {
                obj['silverGramInVnd'] = ApiClient.convertToType(data['silverGramInVnd'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SilverPriceRateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SilverPriceRateDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['gmtOuncePriceUsdUpdated'] && !(typeof data['gmtOuncePriceUsdUpdated'] === 'string' || data['gmtOuncePriceUsdUpdated'] instanceof String)) {
            throw new Error("Expected the field `gmtOuncePriceUsdUpdated` to be a primitive type in the JSON string but got " + data['gmtOuncePriceUsdUpdated']);
        }
        // ensure the json data is a string
        if (data['gmtVndUpdated'] && !(typeof data['gmtVndUpdated'] === 'string' || data['gmtVndUpdated'] instanceof String)) {
            throw new Error("Expected the field `gmtVndUpdated` to be a primitive type in the JSON string but got " + data['gmtVndUpdated']);
        }

        return true;
    }


}



/**
 * @member {Number} silverOunceInVnd
 */
SilverPriceRateDto.prototype['silverOunceInVnd'] = undefined;

/**
 * @member {String} gmtOuncePriceUsdUpdated
 */
SilverPriceRateDto.prototype['gmtOuncePriceUsdUpdated'] = undefined;

/**
 * @member {Number} usdToVnd
 */
SilverPriceRateDto.prototype['usdToVnd'] = undefined;

/**
 * @member {String} gmtVndUpdated
 */
SilverPriceRateDto.prototype['gmtVndUpdated'] = undefined;

/**
 * @member {Number} gramToOunceFormula
 */
SilverPriceRateDto.prototype['gramToOunceFormula'] = undefined;

/**
 * @member {Number} silverGramInUsd
 */
SilverPriceRateDto.prototype['silverGramInUsd'] = undefined;

/**
 * @member {Number} silverGramInVnd
 */
SilverPriceRateDto.prototype['silverGramInVnd'] = undefined;






export default SilverPriceRateDto;

