/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JewelryApis);
  }
}(this, function(expect, JewelryApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JewelryApis.MetalApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetalApi', function() {
    describe('deleteMetal', function() {
      it('should call deleteMetal successfully', function(done) {
        //uncomment below and update the code to test deleteMetal
        //instance.deleteMetal(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllMetalTypes', function() {
      it('should call getAllMetalTypes successfully', function(done) {
        //uncomment below and update the code to test getAllMetalTypes
        //instance.getAllMetalTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllMetalTypesOnMonitor', function() {
      it('should call getAllMetalTypesOnMonitor successfully', function(done) {
        //uncomment below and update the code to test getAllMetalTypesOnMonitor
        //instance.getAllMetalTypesOnMonitor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMetalGoldPriceRate', function() {
      it('should call getMetalGoldPriceRate successfully', function(done) {
        //uncomment below and update the code to test getMetalGoldPriceRate
        //instance.getMetalGoldPriceRate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMetalSilverPriceRate', function() {
      it('should call getMetalSilverPriceRate successfully', function(done) {
        //uncomment below and update the code to test getMetalSilverPriceRate
        //instance.getMetalSilverPriceRate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMetalTypeInDetails', function() {
      it('should call getMetalTypeInDetails successfully', function(done) {
        //uncomment below and update the code to test getMetalTypeInDetails
        //instance.getMetalTypeInDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('insertNewMetal', function() {
      it('should call insertNewMetal successfully', function(done) {
        //uncomment below and update the code to test insertNewMetal
        //instance.insertNewMetal(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMetal', function() {
      it('should call updateMetal successfully', function(done) {
        //uncomment below and update the code to test updateMetal
        //instance.updateMetal(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
