/**
 * Jewelry APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InputValues from '../model/InputValues';
import OutputValues from '../model/OutputValues';

/**
* Warranty service.
* @module api/WarrantyApi
* @version 1.0.0
*/
export default class WarrantyApi {

    /**
    * Constructs a new WarrantyApi. 
    * @alias module:api/WarrantyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createWarranty operation.
     * @callback module:api/WarrantyApi~createWarrantyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OutputValues} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/InputValues} inputValues 
     * @param {module:api/WarrantyApi~createWarrantyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OutputValues}
     */
    createWarranty(inputValues, callback) {
      let postBody = inputValues;
      // verify the required parameter 'inputValues' is set
      if (inputValues === undefined || inputValues === null) {
        throw new Error("Missing the required parameter 'inputValues' when calling createWarranty");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = OutputValues;
      return this.apiClient.callApi(
        '/warranties', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
